version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
